<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto

namespace Grpc\Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inventory.StockResponse</code>
 */
class StockResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>.inventory.StockInfo stock = 3;</code>
     */
    protected $stock = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *     @type string $message
     *     @type \Grpc\Inventory\StockInfo $stock
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.inventory.StockInfo stock = 3;</code>
     * @return \Grpc\Inventory\StockInfo|null
     */
    public function getStock()
    {
        return $this->stock;
    }

    public function hasStock()
    {
        return isset($this->stock);
    }

    public function clearStock()
    {
        unset($this->stock);
    }

    /**
     * Generated from protobuf field <code>.inventory.StockInfo stock = 3;</code>
     * @param \Grpc\Inventory\StockInfo $var
     * @return $this
     */
    public function setStock($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Inventory\StockInfo::class);
        $this->stock = $var;

        return $this;
    }

}

