<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto

namespace Grpc\Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inventory.DeductStockRequest</code>
 */
class DeductStockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .inventory.StockItem items = 1;</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>string order_no = 2;</code>
     */
    protected $order_no = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Grpc\Inventory\StockItem>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type string $order_no
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inventory::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .inventory.StockItem items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .inventory.StockItem items = 1;</code>
     * @param array<\Grpc\Inventory\StockItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Inventory\StockItem::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->order_no;
    }

    /**
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_no = $var;

        return $this;
    }

}

