<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace Grpc\Order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.OrderInfo</code>
 */
class OrderInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string order_no = 2;</code>
     */
    protected $order_no = '';
    /**
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>string total_amount = 4;</code>
     */
    protected $total_amount = '';
    /**
     * Generated from protobuf field <code>int32 status = 5;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>string status_text = 6;</code>
     */
    protected $status_text = '';
    /**
     * Generated from protobuf field <code>string address = 7;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string receiver = 8;</code>
     */
    protected $receiver = '';
    /**
     * Generated from protobuf field <code>string phone = 9;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string remark = 10;</code>
     */
    protected $remark = '';
    /**
     * Generated from protobuf field <code>string paid_at = 11;</code>
     */
    protected $paid_at = '';
    /**
     * Generated from protobuf field <code>string created_at = 12;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>repeated .order.OrderItemInfo items = 13;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $order_no
     *     @type int|string $user_id
     *     @type string $total_amount
     *     @type int $status
     *     @type string $status_text
     *     @type string $address
     *     @type string $receiver
     *     @type string $phone
     *     @type string $remark
     *     @type string $paid_at
     *     @type string $created_at
     *     @type array<\Grpc\Order\OrderItemInfo>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @return string
     */
    public function getOrderNo()
    {
        return $this->order_no;
    }

    /**
     * Generated from protobuf field <code>string order_no = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->order_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>int64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string total_amount = 4;</code>
     * @return string
     */
    public function getTotalAmount()
    {
        return $this->total_amount;
    }

    /**
     * Generated from protobuf field <code>string total_amount = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->total_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status = 5;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status_text = 6;</code>
     * @return string
     */
    public function getStatusText()
    {
        return $this->status_text;
    }

    /**
     * Generated from protobuf field <code>string status_text = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusText($var)
    {
        GPBUtil::checkString($var, True);
        $this->status_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 7;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receiver = 8;</code>
     * @return string
     */
    public function getReceiver()
    {
        return $this->receiver;
    }

    /**
     * Generated from protobuf field <code>string receiver = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiver($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 9;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remark = 10;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->remark;
    }

    /**
     * Generated from protobuf field <code>string remark = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->remark = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string paid_at = 11;</code>
     * @return string
     */
    public function getPaidAt()
    {
        return $this->paid_at;
    }

    /**
     * Generated from protobuf field <code>string paid_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setPaidAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->paid_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 12;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .order.OrderItemInfo items = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .order.OrderItemInfo items = 13;</code>
     * @param array<\Grpc\Order\OrderItemInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Order\OrderItemInfo::class);
        $this->items = $arr;

        return $this;
    }

}

