<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace Grpc\Order;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>order.OrderItemInfo</code>
 */
class OrderItemInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 product_id = 2;</code>
     */
    protected $product_id = 0;
    /**
     * Generated from protobuf field <code>string product_name = 3;</code>
     */
    protected $product_name = '';
    /**
     * Generated from protobuf field <code>string product_image = 4;</code>
     */
    protected $product_image = '';
    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     */
    protected $quantity = 0;
    /**
     * Generated from protobuf field <code>string price = 6;</code>
     */
    protected $price = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $product_id
     *     @type string $product_name
     *     @type string $product_image
     *     @type int $quantity
     *     @type string $price
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 product_id = 2;</code>
     * @return int|string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>int64 product_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkInt64($var);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_name = 3;</code>
     * @return string
     */
    public function getProductName()
    {
        return $this->product_name;
    }

    /**
     * Generated from protobuf field <code>string product_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProductName($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string product_image = 4;</code>
     * @return string
     */
    public function getProductImage()
    {
        return $this->product_image;
    }

    /**
     * Generated from protobuf field <code>string product_image = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProductImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->product_image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string price = 6;</code>
     * @return string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>string price = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->price = $var;

        return $this;
    }

}

